# Generated by Django 4.2.3 on 2023-08-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_body_coment_content_remove_coment_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
